version: '3'

networks:
  default:
    driver: bridge

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./app/:/app:delegated
    ports:
      - '80:80'
    networks:
      - default
    depends_on:
      - db
    user: 1000:1000
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_ROOT_PASSWORD=app
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db